# Utiliza una imagen base de .NET para compilar
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

# Copia los archivos .csproj y restaura dependencias
COPY *.csproj .
RUN dotnet restore

# Copia todo el contenido del proyecto y compila
COPY . .
RUN dotnet publish -c Release -o out

# Etapa final: un runtime optimizado (imagen más liviana)
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app

# Copia los archivos compilados de la etapa build
COPY --from=build /app/out ./

# Puerto que expondrá la aplicación
EXPOSE 8080

# Comando de inicio
ENTRYPOINT ["dotnet", "InventoryAPI.dll"]
